version: 2.1
orbs:
  node: circleci/node@5

workflows:
  build-test-lint:
    jobs:
      - build-test-lint

jobs:
  build-test-lint:
    executor: node/default
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: Install MySQL Client
          command: sudo apt-get install -y mysql-client
      - run:
          name: Set up MySQL
          command: |
            docker run --name mysql -e MYSQL_ROOT_PASSWORD=root -d -p 3306:3306 mysql:5.7
            sleep 20
            mysql -u root -proot -h 127.0.0.1 -e "CREATE DATABASE IF NOT EXISTS restaurant;"
            mysql -u root -proot -h 127.0.0.1 restaurant < setup.sql
      - run:
          name: run test
          command: npm run test
      - run:
          name: run lint
          command: npm run lint
      - run:
          name: deploy app
          command: curl https://api.render.com/deploy/srv-cpuudclds78s739gspt0?key=XhZumxstBUk
