version: 2.1
orbs:
  node: circleci/node@5

workflows:
  build-test-lint:
    jobs:
      - build-test-lint

jobs:
  build-test-lint:
    executor: node/default
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: run test
          command: npm run test
      - run:
          name: run lint
          command: npx eslint src --ignore-pattern src/public/** --ext .js
      - run:
          name: deploy app
          command: curl https://api.render.com/deploy/srv-cpuudclds78s739gspt0?key=XhZumxstBUk
