version: 2.1

orbs:
  node: circleci/node@5

executors:
  node-mysql-executor:
    docker:
      - image: circleci/node:14
      - image: circleci/mysql:5.7
    working_directory: ~/repo

jobs:
  build-test-lint:
    executor: node-mysql-executor
    steps:
      - checkout
      - run:
          name: Wait for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 3306 && echo Success && exit 0
              echo "Waiting for MySQL..."
              sleep 2
            done
            echo "MySQL did not become available in time" && exit 1
      - run:
          name: Set up MySQL
          command: |
            mysql -u root -e "CREATE DATABASE IF NOT EXISTS restaurant;"
            mysql -u root restaurant < setup.sql
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: run test
          command: npm run test
      - run:
          name: run lint
          command: npm run lint
      - run:
          name: deploy app
          command: curl https://api.render.com/deploy/srv-cpuudclds78s739gspt0?key=XhZumxstBUk

workflows:
  build-test-lint:
    jobs:
      - build-test-lint
