version: 2.1
orbs:
  node: circleci/node@5

workflows:
  build-test-lint:
    jobs:
      - build-test-lint

jobs:
  build-test-lint:
    docker:
      - image: circleci/node:14
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: restaurant
    steps:
      - checkout
      - run:
          name: Wait for MySQL to be ready
          command: |
            for i in `seq 1 10`; do
              nc -z localhost 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Set up MySQL
          command: |
            docker run --network host --rm -i -e MYSQL_ROOT_PASSWORD=root mysql:5.7 mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS restaurant;"
            docker run --network host --rm -i -e MYSQL_ROOT_PASSWORD=root mysql:5.7 mysql -u root -proot restaurant < setup.sql
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: run test
          command: npm run test
      - run:
          name: run lint
          command: npm run lint
      - run:
          name: deploy app
          command: curl https://api.render.com/deploy/srv-cpuudclds78s739gspt0?key=XhZumxstBUk
